
###




### Customer API 

#Get Detail User
GET http://localhost:8003/11

###
#Login

POST http://localhost:8003/login
Content-Type: application/json

{
    "email": "lamcoivodoi123@gmail.com",
    "password": "lamcoivodoi123"
}

###
#Signup API

POST http://localhost:8003/signup
Content-Type: application/json

{
    "username": "huyengtrang",
    "email": "lamcoivodoi123@gmail.com",
    "password": "lamcoivodoi123"
}

###
#Update Infor Customer
POST http://localhost:8003/9/add-info
Content-Type: application/json

{
    "address" : "Thi Tran Binh My",
    "phoneNumber" : "0973688222"
}

