version : "3.8"
services:
  product:
    image: product-micro
    container_name: product
    ports:
      - "8001:8001"    
    volumes:
    - .:/app
      - /app/product/node_modules
    depends_on:
    - "mysql_server"
    networks:
      - micro_net

  customer:
    # build:docker 
    #   dockerfile: Dockerfile
    #   context: ./customer
    image: customer-micro:5.0
    container_name: customer
    ports:
      - 8003:8003
    volumes:  
      - .:/app 
    depends_on:
    - "mysql_server"
    networks:
      - micro_net

  shopping:
    # build:
    #   dockerfile: Dockerfile
    #   context: ./shopping
    image: shopping-micro
    container_name: shopping
    ports:
      - "8002:8002"     
    restart: always
    volumes:
      - .:/app
      - /app/shopping/node_modules
    depends_on:
    - "mysql_server"  
    networks:
    - micro_net  


  mysql_server:
    container_name: mysql_server
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_DATABASE=customer_db
    ports: 
    - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - micro_net
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1
    environment:
    - PMA_HOST=mysql_server
    - PMA_ARBITARY=1
    ports:
    - 8085:80 
    networks:
      - micro_net
  
networks:
  micro_net:
    external: true  
  
volumes:
  mysql-data:
