version : '3'
services:
  mysql_server:
    container_name: mysql_server
    image: thanhlam2k4/microservice-mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=thanhlam2k4
     - MYSQL_PASSWORD=room
     - MYSQL_DATABASE=customer_db
    networks:
     - micro-dev-net
  front_end:
    container_name: front_end
    image: thanhlam2k4/microservice-fe
    ports:
    - "3000:3000"
    restart: always
    depends_on:
    - "mysql_server"
    networks:
      - micro-dev-net
  customer:
    container_name: customer
    image: thanhlam2k4/microservice-customer
    ports:
      - "8003:8003" 
    restart: always
    depends_on:
    - "mysql_server"
    networks:
      - micro-dev-net
  product:
    container_name: product
    image: thanhlam2k4/microservice-product
    ports:
      - "8001:8001" 
    restart: always
    depends_on:
    - "mysql_server"
    networks:
      - micro-dev-net
networks:
  micro-dev-net:
    external: true  