
###




### Customer API 

#Get Detail User
GET http://192.168.56.105:8003/1

###192.168.56.105:8001/api/v1/data
#Login

POST http://localhost:8003/login
Content-Type: application/json

{
    "email": "huyentrang@gmail.com",
    "password": "lamcoivodoi123"
}

###
#Signup API

POST http://localhost:8003/signup
Content-Type: application/json

{
    "username": "huyengtrang",
    "email": "lamcoivodoi123@gmail.com",
    "password": "lamcoivodoi123"
}

###
POST http://localhost/customer/signup
Content-Type: application/json

{
    "username": "thanhlam",
    "email": "huyentrang@gmail.com",
    "password": "lamcoivodoi123"
}

###
#Update Infor Customer
POST http://localhost:8003/9/add-info
Content-Type: application/json

{
    "address" : "Thi Tran Binh My",
    "phoneNumber" : "0973688222"
}

