version : "3.8"
services: 
  test-app:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: testapp
    ports:
      - 3000:3000 
    restart: always  
    volumes:
      - .:/app