version : "3.8"
services:
 
  mysql_server:
    container_name: mysql_server
    image: thanhlam2k4/mysql-pre-schema
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_DATABASE=customer_db
    ports: 
    - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - micro_net

networks:
  micro_net:
    external: true  
  
volumes:
  mysql-data:
